### ISSUE TITLE
Error: local variable revision referenced before assignment 

### ISSUE THREAD

**Issue by stefiix92** [kjagiello/terraform-aws-codepipeline-slack-notifications#18]
Hi,

in the v1.1.4 the code sometimes throws an error

```
[ERROR] UnboundLocalError: local variable 'revision' referenced before assignment
Traceback (most recent call last):
  File "/var/task/notifier.py", line 129, in handler
    payload = build_slack_message_from_event(event)
  File "/var/task/notifier.py", line 93, in build_slack_message_from_event
    attachment = format_slack_attachment(
  File "/var/task/notifier.py", line 60, in format_slack_attachment
    *revision,
```

and no event is pushed to the Slack channel

**Comment by kjagiello** [comment]
Merged and released in [v1.1.5](https://github.com/kjagiello/terraform-aws-codepipeline-slack-notifications/releases/tag/v1.1.5). Thanks for your report and contribution!
